#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run TypeScript compiler on staged files
yarn tsc --project tsconfig.json --noEmit || exit 1

# Run formatter on staged files
yarn biome format --check || exit 1

# Run Biome on staged files via lint-staged
yarn lint-staged
